import { ContentRecord } from './types';

export const demoData: ContentRecord[] = [
  {
    id: 'DEMO-001',
    kind: 'modlitwa',
    title: '[DEMO] Modlitwa poranna',
    category: 'Codzienne',
    text: 'To jest tekst demonstracyjny modlitwy porannej, używany tylko do celów testowych.',
    source: 'Tradycja demonstracyjna, wariant A',
    rightsStatus: 'public_domain',
    explanation3to6: 'Budzimy się i witamy z Bogiem.',
    explanation7to12: 'Każdy dzień zaczynamy od powierzenia się opiece Boga, dziękując za noc.',
    editorialStatus: 'approved',
    recordingStatus: 'verified',
    audioPath: '/audio/demo-001.mp3',
    updatedAt: new Date(Date.now() - 100000000).toISOString(),
  },
  {
    id: 'DEMO-002',
    kind: 'tekst mszalny',
    title: '[DEMO] Akt pokuty',
    category: 'Msza Święta',
    text: 'Tekst demonstracyjny aktu pokuty.',
    source: 'Mszał Rzymski (demo)',
    rightsStatus: 'public_domain',
    explanation3to6: 'Przepraszamy Boga za złe rzeczy.',
    explanation7to12: 'Akt pokuty to moment, w którym uznajemy nasze słabości i prosimy Boga o miłosierdzie przed rozpoczęciem sprawowania ofiary mszalnej.',
    editorialStatus: 'review',
    recordingStatus: 'missing',
    audioPath: '',
    updatedAt: new Date(Date.now() - 50000000).toISOString(),
  },
  {
    id: 'DEMO-003',
    kind: 'wykaz katechizmowy',
    title: '[DEMO] Główne prawdy wiary',
    category: 'Katechizm',
    text: '1. Jest jeden Bóg.\\n2. Bóg jest sędzią sprawiedliwym...',
    source: 'Katechizm (demo)',
    rightsStatus: 'public_domain',
    explanation3to6: 'Najważniejsze rzeczy o Bogu.',
    explanation7to12: 'Podstawowe prawdy, w które wierzymy jako katolicy, stanowiące fundament naszej wiary.',
    editorialStatus: 'approved',
    recordingStatus: 'recorded',
    audioPath: '/audio/demo-003.mp3',
    updatedAt: new Date(Date.now() - 20000000).toISOString(),
  },
  {
    id: 'DEMO-004',
    kind: 'tajemnica różańcowa',
    title: '[DEMO] Zwiastowanie',
    category: 'Różaniec - Radosne',
    text: 'Tekst demonstracyjny rozważania tajemnicy zwiastowania.',
    source: 'Opracowanie własne (demo)',
    rightsStatus: 'licensed',
    explanation3to6: 'Anioł mówi Maryi, że będzie mamą Jezusa.',
    explanation7to12: 'Archanioł Gabriel zwiastuje Maryi, że została wybrana na Matkę Zbawiciela. Maryja odpowiada "tak" na Boży plan.',
    editorialStatus: 'draft',
    recordingStatus: 'missing',
    audioPath: '',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'DEMO-005',
    kind: 'rozważanie',
    title: '[DEMO] Droga Krzyżowa - Stacja I',
    category: 'Wielki Post',
    text: 'Tekst demonstracyjny stacji pierwszej.',
    source: 'Opracowanie redakcji (demo)',
    rightsStatus: 'licensed',
    explanation3to6: 'Pan Jezus jest niesprawiedliwie osądzony.',
    explanation7to12: 'Jezus, choć niewinny, przyjmuje niesprawiedliwy wyrok w milczeniu, pokazując nam, jak znosić trudności.',
    editorialStatus: 'rejected',
    recordingStatus: 'missing',
    audioPath: '',
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  }
];
